/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LIM
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginForm() {
        initComponents();
        
        // This place the JFrame at the center of the secreen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2-getHeight()/2);
        
        ImageIcon icon = new ImageIcon("src\\Image\\company_logo.png");
        this.setIconImage(icon.getImage());
        
    }
    
    Connection con = MyConnection.getConnection();
    PreparedStatement pst;
    ResultSet rs;
    
    public void currentDate(){
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        String date = ((month+1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        String time = ((hour+00)+":"+(minute+00)+":"+(second+00));
        System.out.println(date+" "+time);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 560));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Century Gothic", 3, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Payroll Management System");
        jPanel3.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 370, 40));

        lblTitle1.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("v.1.0.0");
        jPanel3.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 70, 40));

        lblUsername1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username");
        jPanel3.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 90, -1));

        lblPassword.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel3.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 90, -1));

        tfUsername.setBackground(new java.awt.Color(255, 255, 255));
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfUsername.setSelectionStart(20);
        jPanel3.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 310, 40));

        pfPassword.setBackground(new java.awt.Color(255, 255, 255));
        pfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pfPassword.setSelectionStart(20);
        jPanel3.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 310, 40));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Book Antiqua", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 82, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background-image.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 400, 540));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/companylogo_background.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 540, 540));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        Main main = new Main();

        String username = tfUsername.getText();
        String password = String.valueOf(pfPassword.getPassword());

        String query = "SELECT * FROM `accounts` WHERE `username`=? AND `password`=?";

        try
        {
            pst = con.prepareStatement(query);

            pst.setString(1, username);
            pst.setString(2, password);

            rs = pst.executeQuery();

            boolean checkUser = main.checkUsername(username);
            boolean checkPass = main.checkPassword(password);

            if(rs.next())
            {
                // Retrieve id of admin after login
                int id = rs.getInt(1);
                Main.adminId = id;
                
                JOptionPane.showMessageDialog(null, "Login Successfully");
                Employee emp = new Employee();
                this.hide();
                emp.show();
                
                
                try{
                    // Retrieve admin_id and admin_name that will match to the inputted username in login form
                    String query2 = "SELECT `id`, `name` FROM `accounts` WHERE username=?";
                    pst = con.prepareStatement(query2);
                    pst.setString(1, tfUsername.getText());
                    rs = pst.executeQuery();
                    
                    if(rs.next()){
                        // Get current time and date
                        Calendar cal = new GregorianCalendar();
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);
                        int day = cal.get(Calendar.DAY_OF_MONTH);
                        
                        int second = cal.get(Calendar.SECOND);
                        int minute = cal.get(Calendar.MINUTE);
                        int hour = cal.get(Calendar.HOUR);

                        // retrieved data
                        String adminId = rs.getString("id");
                        String adminName = rs.getString("name");
                        String date = ((month+1)+"/"+day+"/"+year);
                        String time = ((hour+00)+":"+(minute+00)+":"+(second+00));
                        
                        // for description
                        String desc = "Logged in the system";
                        
                        // Insert retrieved data into account login
                        String query3 = "INSERT INTO `account_login`(`admin_id`, `admin_name`, `login_date`, `login_time`, `description`) VALUES (?, ?, ?, ?, ?)";
                        pst = con.prepareStatement(query3);
                        pst.setString(1, adminId);
                        pst.setString(2, adminName);
                        pst.setString(5, desc);
                        pst.setString(3, date);
                        pst.setString(4, time);
                        
                        pst.execute();
                    }
                    
                }catch(SQLException e){
                    
                }
            }
            else{
                if((tfUsername.getText()).equals("")){
                    JOptionPane.showMessageDialog(null, "Please enter your username and password.");
                }
                else if(checkUser == false){
                    JOptionPane.showMessageDialog(null, "Username does not exist.");
                }
                else if((pfPassword.getText()).equals("")){
                    JOptionPane.showMessageDialog(null, "Please enter your password.");
                }
                else if(checkPass == false){
                    JOptionPane.showMessageDialog(null, "Password is incorrect.");
                }
            }
            
        }
        catch(SQLException ex)
        {
            
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
        try{
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("C:\\Users\\LIM\\Documents\\NetBeansProjects\\JA\\src\\Image\\company_logo.jpg")));

        }catch(Exception e){
            
        }
        
    }
}
